spring:
   datasource:
      driverClassName: org.h2.Driver
      url: jdbc:h2:file:./tmp/customer
      username: sa
      password:
   
   thymeleaf:
      cache: false 
   
   jpa:
      hibernate.ddl-auto: validate
      
      
security:
      basic:
         enabled: false


logging:
   level:
      root: INFO
      org.hibernate: WARN
      org.hibernate.SQL: DEBUG
